server:
  port: 7001

spring:
  application:
    name: config-server
  profiles:
      active: server1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mb0517/spring-cloud-learning/
          search-paths: config-repo
#          username: *****
#          password: *****

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

management:
  security:
    enabled: false